# base_de_conocimientos.py

animes = [
    {'nombre': 'Tokyo Ghoul', 'genero': 'gore', 'calificacion': 7.9},
    {'nombre': 'Elfen Lied', 'genero': 'gore', 'calificacion': 7.6},
    {'nombre': 'Higurashi no Naku Koro ni', 'genero': 'gore', 'calificacion': 8.0},
    {'nombre': 'Another', 'genero': 'gore', 'calificacion': 7.5},
    {'nombre': 'Attack on Titan', 'genero': 'gore', 'calificacion': 9.1},
    {'nombre': 'High School DxD', 'genero': 'harem', 'calificacion': 7.3},
    {'nombre': 'To Love-Ru', 'genero': 'harem', 'calificacion': 7.0},
    {'nombre': 'Nisekoi', 'genero': 'harem', 'calificacion': 7.6},
    {'nombre': 'The World God Only Knows', 'genero': 'harem', 'calificacion': 7.7},
    {'nombre': 'Rosario + Vampire', 'genero': 'harem', 'calificacion': 6.9},
    {'nombre': 'Fullmetal Alchemist: Brotherhood', 'genero': 'fantasia', 'calificacion': 9.2},
    {'nombre': 'Sword Art Online', 'genero': 'fantasia', 'calificacion': 7.8},
    {'nombre': 'Re:Zero - Starting Life in Another World', 'genero': 'fantasia', 'calificacion': 8.3},
    {'nombre': 'Fate/Stay Night: Unlimited Blade Works', 'genero': 'fantasia', 'calificacion': 8.2},
    {'nombre': 'Overlord', 'genero': 'fantasia', 'calificacion': 7.9},
    {'nombre': 'One Piece', 'genero': 'aventura', 'calificacion': 8.9},
    {'nombre': 'Naruto', 'genero': 'aventura', 'calificacion': 8.3},
    {'nombre': 'Fairy Tail', 'genero': 'aventura', 'calificacion': 7.9},
    {'nombre': 'Hunter x Hunter', 'genero': 'aventura', 'calificacion': 9.0},
    {'nombre': 'Made in Abyss', 'genero': 'aventura', 'calificacion': 8.8},
    {'nombre': 'Clannad: After Story', 'genero': 'romance', 'calificacion': 8.9},
    {'nombre': 'Toradora!', 'genero': 'romance', 'calificacion': 8.0},
    {'nombre': 'Your Lie in April', 'genero': 'romance', 'calificacion': 8.7},
    {'nombre': 'Kimi ni Todoke', 'genero': 'romance', 'calificacion': 7.8},
    {'nombre': 'Fruits Basket', 'genero': 'romance', 'calificacion': 8.5},
    # Añadir más animes si es necesario
]
